server:
  port: 8080

cache:
  dir: cache
git:
  remoteName: ${GIT_REMOTE_NAME:origin}
  remoteUrl: ${GIT_REMOTE_URL}
  user: ${GIT_USER}
  token: ${GIT_TOKEN}
argocd:
  origin: ${ARGOCD_ORIGIN:https://localhost:18080}
  token: ${ARGOCD_TOKEN}
  project: ${ARGOCD_PROJECT:network-policy-manager}