# values.yaml
name: example-network-policy
namespace: example
selector:
  app: example-app
ingress:
  from:
    - ipBlock:
        cidr: 172.17.0.0/16
  ports:
    - protocol: TCP
      port: 80
egress:
  to:
    - ipBlock:
        cidr: 10.0.0.0/24
  ports:
    - protocol: TCP
      port: 443
